### PR TITLE
3.2 - The Hadron Update

### PR DESCRIPTION
**Pull request by DylanFPS**
_Prison 4 has become Prison 3.2 as we don't have enough time to make a feature-full update to justify a major version buff_
<h1 align="center">The Hadron Update</h1>

## Notes
- Prison 3.2.4 is planned to be a long-term support (LTS) version. This is so we can update Prison 3.2 so it's stable enough to continue to work without updates
- **~~Crossed out~~ fields represent those that need to be renegotiated due to time constraints** @faizaand 

## Internals
- [ ] ~~Add SQL and Mongo backends for storage~~
- [ ] ~~Integration with Sponge and Nukkit (:o)~~

## Mines
- [ ] ~~Percentage-based mine resets (#65)~~
- [ ] Placeholders to show mine status (how empty it is, time until next reset, etc.)
- [ ] ~~Inbuilt mine protection (while maintaining Worldguard compat)~~
- [ ] ~~Lucky blocks!!!~~
- [ ] Autopickup, autosmelt, autoblock, and mining boosts (#58)
- [ ] Teleporting to mines (maybe /mymine command?)

## Ranks
- [ ] Set/reset ranks ingame
- [ ] Prestige (#68)
- [ ] ~~Optional inhouse economy system with Vault integration~~
- [x] Placeholders (current rank, next rank, cost of next rank, amount needed to rankup, percentage, progress bar)
- [x] Localization support

### CODE REVIEW

**Comment by ThisInsider** [comment]
This little update is a great thing but its missing #89 since my server is HIGHLY DEPENDENT on different block data, can you please prioritize that issue?

**Comment by DylanFPS** [comment]
We’re still not going to implement #89. It has been removed after years of deprecation, we all need to move on from an old system and use the name system.

**Comment by DylanFPS** [comment]
We will obviously use the new naming system (I.e. Minecraft:redstone_block and redstone_block)

**Comment by DylanFPS** [comment]
Assuming you're on about the `id:data` format, no we won't save these values. They clearly aren't crucial as Mojang have removed them in 1.13. They've given everyone plenty of warning for this ever since 1.8.

**Comment by ThisInsider** [comment]
My bad, I did not know that blocks with data values have their own unique names now in 1.13

**Pull request closed without merging**
