### PR TITLE
Update zh-CN.properties

### PR DESCRIPTION
**Pull request by SnowCutieOwO**
idk why but there's bunch corrupted code, I fixed it and re-translated some of them as the original wasn't very good

### CODE REVIEW

**Comment by rbluer** [comment]
I'm just seeing your pull request now.   Sorry for the delay.

Thank you for  providing some updates to this file!  We greatly appreciate your help!  

You mentioned that some of the messages appeared to be corrupted?  I've seen this before when someone might have edited the file without using UTF-8.  I could have caused that issue when adding new messages to this group.

Can you please reissue your pull request to PrisonTeam:bleeding?  The PrisonTeam:master is protected and we do not want to pull anything directly in to it, without first testing within our bleeding branch.

If you need anything, or want to discuss this, please reach out to me on our discord server.  

Thanks for your help!
   RoyalBlueRanger

**Comment by SnowCutieOwO** [comment]
> I'm just seeing your pull request now.   Sorry for the delay.
> 
> Thank you for  providing some updates to this file!  We greatly appreciate your help!  
> 
> You mentioned that some of the messages appeared to be corrupted?  I've seen this before when someone might have edited the file without using UTF-8.  I could have caused that issue when adding new messages to this group.
> 
> Can you please reissue your pull request to PrisonTeam:bleeding?  The PrisonTeam:master is protected and we do not want to pull anything directly in to it, without first testing within our bleeding branch.
> 
> If you need anything, or want to discuss this, please reach out to me on our discord server.  
> 
> Thanks for your help!
>    RoyalBlueRanger

Whoa! Thanks for reply, and I would happy to if you could give me the link of repo :) I'll check it later

**Comment by rbluer** [comment]
It's this one... same repo, just different branch.  You may be able to just change the target branch on the PR?  I cannot change that myself, but you may?

https://github.com/PrisonTeam/Prison/tree/bleeding

**Comment by SnowCutieOwO** [comment]
> It's this one... same repo, just different branch. You may be able to just change the target branch on the PR? I cannot change that myself, but you may?
> 
> https://github.com/PrisonTeam/Prison/tree/bleeding

Good, I'll close this pull quest and open another one :)

**Pull request closed without merging**
