### PR TITLE
Added spanish localization

### PR DESCRIPTION
**Pull request by vicentefelipechile**
what the title says

### CODE REVIEW

**Comment by rbluer** [comment]
I'm sorry, I am just now seeing this pull request.

Thank you for your work on this contribute.  I think this is excellent in how much you've updated and provided.

Could you please reopen this pull request to the target branch of PrisonTeam:bleeding?  We don't pull to PrisonTeam:Master until we are able to test everything; that is a restricted branch.

If you have any questions, or would like to discuss anything, please reach out to me on our discord server.
    RoyalBlueRanger

**Comment by rbluer** [comment]
Vinentefelipechile,

I did not want this to fall through the cracks.  So I'm wanting to remind you that if you could just change the target branch to `Prison:bleeding` I can get it pulled in and include with our development and alpha builds.

Thanks!

**Comment by vicentefelipechile** [comment]
I'm sorry for not answering before, what I wanted to mention is how can I change the target of the pull request to the other branch?

**Comment by rbluer** [comment]
You may have to close the PR and create a new one.   I personally am not a github power user, so I have not been able to figure that out myself.  I suspect it's just easier to open a new PR so they never added the feature to change the targets?

**Pull request closed without merging**
